import { type Language, type SyntaxToken } from './coding-practice.types';

// ─────────────────────────────────────────────
// Syntax Tokens per language
// ─────────────────────────────────────────────

export const JAVASCRIPT_TOKENS: SyntaxToken[] = [
  // Keywords
  { id: 'kw_class', label: 'class', category: 'keyword' },
  { id: 'kw_function', label: 'function', category: 'keyword' },
  { id: 'kw_const', label: 'const', category: 'keyword' },
  { id: 'kw_let', label: 'let', category: 'keyword' },
  { id: 'kw_var', label: 'var', category: 'keyword' },
  { id: 'kw_return', label: 'return', category: 'keyword' },
  { id: 'kw_new', label: 'new', category: 'keyword' },
  { id: 'kw_this', label: 'this', category: 'keyword' },
  { id: 'kw_extends', label: 'extends', category: 'keyword' },
  { id: 'kw_if', label: 'if', category: 'keyword' },
  { id: 'kw_else', label: 'else', category: 'keyword' },
  { id: 'kw_for', label: 'for', category: 'keyword' },
  { id: 'kw_while', label: 'while', category: 'keyword' },
  { id: 'kw_constructor', label: 'constructor', category: 'keyword' },
  { id: 'kw_async', label: 'async', category: 'keyword' },
  { id: 'kw_await', label: 'await', category: 'keyword' },
  { id: 'kw_super', label: 'super', category: 'keyword' },
  { id: 'kw_switch', label: 'switch', category: 'keyword' },
  { id: 'kw_case', label: 'case', category: 'keyword' },
  { id: 'kw_break', label: 'break', category: 'keyword' },
  { id: 'kw_try', label: 'try', category: 'keyword' },
  { id: 'kw_catch', label: 'catch', category: 'keyword' },
  { id: 'kw_finally', label: 'finally', category: 'keyword' },
  { id: 'kw_throw', label: 'throw', category: 'keyword' },
  { id: 'kw_export', label: 'export', category: 'keyword' },
  { id: 'kw_import', label: 'import', category: 'keyword' },
  { id: 'kw_default', label: 'default', category: 'keyword' },
  { id: 'kw_from', label: 'from', category: 'keyword' },
  { id: 'kw_yield', label: 'yield', category: 'keyword' },
  { id: 'kw_of', label: 'of', category: 'keyword' },
  { id: 'kw_in', label: 'in', category: 'keyword' },
  { id: 'kw_get', label: 'get', category: 'keyword' },
  { id: 'kw_set', label: 'set', category: 'keyword' },
  { id: 'kw_as', label: 'as', category: 'keyword' },
  // Symbols
  { id: 'sym_open_brace', label: '{', category: 'symbol' },
  { id: 'sym_close_brace', label: '}', category: 'symbol' },
  { id: 'sym_open_paren', label: '(', category: 'symbol' },
  { id: 'sym_close_paren', label: ')', category: 'symbol' },
  { id: 'sym_open_bracket', label: '[', category: 'symbol' },
  { id: 'sym_close_bracket', label: ']', category: 'symbol' },
  { id: 'sym_semicolon', label: ';', category: 'symbol' },
  { id: 'sym_comma', label: ',', category: 'symbol' },
  { id: 'sym_dot', label: '.', category: 'symbol' },
  { id: 'sym_colon', label: ':', category: 'symbol' },
  { id: 'sym_equals', label: '=', category: 'operator' },
  { id: 'sym_arrow', label: '=>', category: 'operator' },
  { id: 'sym_gte', label: '>=', category: 'operator' },
  { id: 'sym_lt', label: '<', category: 'operator' },
  { id: 'sym_increment', label: '++', category: 'operator' },
  { id: 'sym_asterisk', label: '*', category: 'operator' },
  { id: 'sym_plus', label: '+', category: 'operator' },
  { id: 'sym_percent', label: '%', category: 'operator' },
  { id: 'sym_double_equals', label: '===', category: 'operator' },
  { id: 'sym_spread', label: '...', category: 'operator' },
  { id: 'sym_opt_chain', label: '?.', category: 'operator' },
  { id: 'sym_nullish', label: '??', category: 'operator' },
  { id: 'sym_question', label: '?', category: 'symbol' },
  { id: 'sym_backtick', label: '`', category: 'symbol' },
  { id: 'sym_dollar_brace', label: '${', category: 'symbol' },
  // Editable identifiers — generic (label overridden per-exercise via tokenLabels)
  { id: 'id_classname', label: 'NomeClasse', category: 'identifier', editable: true },
  { id: 'id_funcname', label: 'nomeFuncao', category: 'identifier', editable: true },
  { id: 'id_varname', label: 'nomeVariavel', category: 'identifier', editable: true },
  { id: 'id_param', label: 'parâmetro 1', category: 'identifier', editable: true },
  { id: 'id_param2', label: 'parâmetro 2', category: 'identifier', editable: true },
  { id: 'id_propname', label: 'propriedade', category: 'identifier', editable: true },
  { id: 'id_methodname', label: 'nomeMetodo', category: 'identifier', editable: true },
  { id: 'id_arrayname', label: 'nomeArray', category: 'identifier', editable: true },
  { id: 'id_newarray', label: 'novoArray', category: 'identifier', editable: true },
  { id: 'id_array1', label: 'array1', category: 'identifier', editable: true },
  { id: 'id_array2', label: 'array2', category: 'identifier', editable: true },
  { id: 'id_objname', label: 'nomeObjeto', category: 'identifier', editable: true },
  { id: 'id_prop1', label: 'propriedade1', category: 'identifier', editable: true },
  { id: 'id_prop2', label: 'propriedade2', category: 'identifier', editable: true },
  { id: 'id_condition', label: 'condicao', category: 'identifier', editable: true },
  { id: 'id_result', label: 'resultado', category: 'identifier', editable: true },
  { id: 'id_parentclass', label: 'ClassePai', category: 'identifier', editable: true },
  { id: 'id_method', label: 'nomeMetodo', category: 'identifier', editable: true },
  { id: 'id_acc', label: 'acc', category: 'identifier', editable: true },
  { id: 'id_curr', label: 'curr', category: 'identifier', editable: true },
  { id: 'id_callfunc', label: 'funcao', category: 'identifier', editable: true },
  { id: 'id_func', label: 'funcao', category: 'identifier', editable: true },
  { id: 'id_var', label: 'variavel', category: 'identifier', editable: true },
  { id: 'id_res', label: 'resultado', category: 'identifier', editable: true },
  { id: 'id_p1', label: 'param1', category: 'identifier', editable: true },
  { id: 'id_p2', label: 'param2', category: 'identifier', editable: true },
  { id: 'id_cond', label: 'condicao', category: 'identifier', editable: true },
  { id: 'id_const', label: 'constante', category: 'identifier', editable: true },
  { id: 'id_arr', label: 'array', category: 'identifier', editable: true },
  { id: 'id_iter', label: 'item', category: 'identifier', editable: true },
  { id: 'id_class', label: 'Classe', category: 'identifier', editable: true },
  { id: 'id_getter', label: 'getter', category: 'identifier', editable: true },
  { id: 'id_obj', label: 'objeto', category: 'identifier', editable: true },
  { id: 'id_global', label: 'global', category: 'identifier', editable: true },
  { id: 'id_alias', label: 'alias', category: 'identifier', editable: true },
  { id: 'id_parent', label: 'Pai', category: 'identifier', editable: true },
  { id: 'id_interp', label: 'valor', category: 'identifier', editable: true },
  // Literals — generic
  { id: 'lit_string', label: '"texto"', category: 'literal', editable: true },
  { id: 'lit_string_1', label: '"valor1"', category: 'literal', editable: true },
  { id: 'lit_string_2', label: '"valor2"', category: 'literal', editable: true },
  { id: 'lit_string_3', label: '"valor3"', category: 'literal', editable: true },
  { id: 'lit_string_adulto', label: '"adulto"', category: 'literal', editable: true },
  { id: 'lit_string_menor', label: '"menor"', category: 'literal', editable: true },
  { id: 'lit_string_true', label: '"verdadeiro"', category: 'literal', editable: true },
  { id: 'lit_string_false', label: '"falso"', category: 'literal', editable: true },
  { id: 'lit_number', label: '0', category: 'literal', editable: true },
  { id: 'lit_number_0', label: '0', category: 'literal', editable: true },
  { id: 'lit_number_2', label: '2', category: 'literal', editable: true },
  { id: 'lit_number_5', label: '5', category: 'literal', editable: true },
  { id: 'lit_ms', label: '1000', category: 'literal', editable: true },
  { id: 'lit_url', label: '"url"', category: 'literal', editable: true },
  { id: 'lit_prop', label: '"prop"', category: 'literal', editable: true },
  { id: 'lit_str', label: '"texto"', category: 'literal', editable: true },
  { id: 'lit_path', label: '"caminho"', category: 'literal', editable: true },
  { id: 'lit_str_part', label: '"parte"', category: 'literal', editable: true },
  { id: 'lit_default', label: '"padrao"', category: 'literal', editable: true },
  { id: 'lit_query', label: '".classe"', category: 'literal', editable: true },
  { id: 'lit_key', label: '"chave"', category: 'literal', editable: true },
  { id: 'lit_val', label: '"valor"', category: 'literal', editable: true },
  { id: 'lit_true', label: 'true', category: 'literal' },
  { id: 'lit_false', label: 'false', category: 'literal' },
  { id: 'lit_null', label: 'null', category: 'literal' },
  // Standard Globals
  { id: 'id_promise', label: 'Promise', category: 'identifier' },
  { id: 'id_json', label: 'JSON', category: 'identifier' },
  { id: 'id_console', label: 'console', category: 'identifier' },
  { id: 'id_window', label: 'window', category: 'identifier' },
  { id: 'id_document', label: 'document', category: 'identifier' },
  { id: 'id_error', label: 'Error', category: 'identifier' },
];

export const JAVA_TOKENS: SyntaxToken[] = [
  // Keywords
  { id: 'kw_class', label: 'class', category: 'keyword' },
  { id: 'kw_if', label: 'if', category: 'keyword' },
  { id: 'kw_else', label: 'else', category: 'keyword' },
  { id: 'kw_for', label: 'for', category: 'keyword' },
  { id: 'kw_while', label: 'while', category: 'keyword' },
  { id: 'kw_return', label: 'return', category: 'keyword' },
  { id: 'kw_new', label: 'new', category: 'keyword' },
  { id: 'kw_this', label: 'this', category: 'keyword' },
  { id: 'kw_super', label: 'super', category: 'keyword' },
  { id: 'kw_switch', label: 'switch', category: 'keyword' },
  { id: 'kw_try', label: 'try', category: 'keyword' },
  { id: 'kw_catch', label: 'catch', category: 'keyword' },
  { id: 'kw_ext', label: 'extends', category: 'keyword' },
  { id: 'kw_impl', label: 'implements', category: 'keyword' },
  { id: 'kw_final', label: 'final', category: 'modifier' },
  // Modifiers
  { id: 'kw_mod', label: 'public', category: 'modifier' },
  { id: 'kw_pub', label: 'public', category: 'modifier' },
  { id: 'kw_stat', label: 'static', category: 'modifier' },
  // Types
  { id: 'kw_void', label: 'void', category: 'type' },
  { id: 'kw_type', label: 'tipo', category: 'type', editable: true },
  { id: 'kw_ret', label: 'tipoRetorno', category: 'type', editable: true },
  { id: 'id_type', label: 'Tipo', category: 'type', editable: true },
  // Symbols
  { id: 'sym_open_brace', label: '{', category: 'symbol' },
  { id: 'sym_close_brace', label: '}', category: 'symbol' },
  { id: 'sym_open_paren', label: '(', category: 'symbol' },
  { id: 'sym_close_paren', label: ')', category: 'symbol' },
  { id: 'sym_open_bracket', label: '[', category: 'symbol' },
  { id: 'sym_close_bracket', label: ']', category: 'symbol' },
  { id: 'sym_semicolon', label: ';', category: 'symbol' },
  { id: 'sym_comma', label: ',', category: 'symbol' },
  { id: 'sym_dot', label: '.', category: 'symbol' },
  // Operators
  { id: 'op_assign', label: '=', category: 'operator' },
  { id: 'op_gte', label: '>=', category: 'operator' },
  { id: 'op_lt', label: '<', category: 'operator' },
  { id: 'op_eq', label: '==', category: 'operator' },
  { id: 'op_inc', label: '++', category: 'operator' },
  { id: 'op_plus', label: '+', category: 'operator' },
  // Editable identifiers
  { id: 'id_class', label: 'NomeClasse', category: 'identifier', editable: true },
  { id: 'id_out', label: 'out', category: 'identifier', editable: true },
  { id: 'id_method', label: 'metodo', category: 'identifier', editable: true },
  { id: 'id_var', label: 'variavel', category: 'identifier', editable: true },
  { id: 'id_name', label: 'nome', category: 'identifier', editable: true },
  { id: 'id_i', label: 'i', category: 'identifier', editable: true },
  { id: 'id_param', label: 'parametro', category: 'identifier', editable: true },
  { id: 'id_attr', label: 'atributo', category: 'identifier', editable: true },
  { id: 'id_list', label: 'lista', category: 'identifier', editable: true },
  { id: 'id_child', label: 'Filho', category: 'identifier', editable: true },
  { id: 'id_parent', label: 'Pai', category: 'identifier', editable: true },
  { id: 'id_inter', label: 'Interface', category: 'identifier', editable: true },
  { id: 'id_ex', label: 'Exception', category: 'identifier', editable: true },
  { id: 'id_res', label: 'resultado', category: 'identifier', editable: true },
  { id: 'id_a', label: 'a', category: 'identifier', editable: true },
  { id: 'id_b', label: 'b', category: 'identifier', editable: true },
  { id: 'id_main', label: 'main', category: 'identifier', editable: true },
  { id: 'id_n', label: 'n', category: 'identifier', editable: true },
  { id: 'id_arr', label: 'array', category: 'identifier', editable: true },
  { id: 'p1', label: 'param1', category: 'identifier', editable: true },
  { id: 'p2', label: 'param2', category: 'identifier', editable: true },
  // Literals
  { id: 'val_string', label: '"texto"', category: 'literal', editable: true },
  { id: 'val_str', label: '"texto"', category: 'literal', editable: true },
  { id: 'val_num', label: '0', category: 'literal', editable: true },
  { id: 'val', label: '0', category: 'literal', editable: true },
  { id: 'val_0', label: '0', category: 'literal', editable: true },
  { id: 'val_1', label: '1', category: 'literal', editable: true },
  { id: 'val_2', label: '2', category: 'literal', editable: true },
  { id: 'val_3', label: '3', category: 'literal', editable: true },
  { id: 'val_5', label: '5', category: 'literal', editable: true },
  { id: 'val_10', label: '10', category: 'literal', editable: true },
  { id: 'val_idx', label: '0', category: 'literal', editable: true },
  { id: 'lit_true', label: 'true', category: 'literal' },
  { id: 'lit_false', label: 'false', category: 'literal' },
  { id: 'lit_null', label: 'null', category: 'literal' },
];

export const CSHARP_TOKENS: SyntaxToken[] = [
  // Keywords
  { id: 'kw_class', label: 'class', category: 'keyword' },
  { id: 'kw_if', label: 'if', category: 'keyword' },
  { id: 'kw_else', label: 'else', category: 'keyword' },
  { id: 'kw_for', label: 'for', category: 'keyword' },
  { id: 'kw_foreach', label: 'foreach', category: 'keyword' },
  { id: 'kw_in', label: 'in', category: 'keyword' },
  { id: 'kw_var', label: 'var', category: 'keyword' },
  { id: 'kw_new', label: 'new', category: 'keyword' },
  { id: 'kw_return', label: 'return', category: 'keyword' },
  { id: 'kw_base', label: 'base', category: 'keyword' },
  { id: 'kw_this', label: 'this', category: 'keyword' },
  { id: 'kw_using', label: 'using', category: 'keyword' },
  { id: 'kw_ns', label: 'namespace', category: 'keyword' },
  { id: 'kw_interface', label: 'interface', category: 'keyword' },
  { id: 'kw_enum', label: 'enum', category: 'keyword' },
  { id: 'kw_struct', label: 'struct', category: 'keyword' },
  { id: 'kw_get', label: 'get', category: 'keyword' },
  { id: 'kw_set', label: 'set', category: 'keyword' },
  { id: 'kw_async', label: 'async', category: 'keyword' },
  { id: 'kw_null', label: 'null', category: 'keyword' },
  // Modifiers
  { id: 'kw_pub', label: 'public', category: 'modifier' },
  { id: 'kw_priv', label: 'private', category: 'modifier' },
  { id: 'kw_ro', label: 'readonly', category: 'modifier' },
  // Types
  { id: 'kw_void', label: 'void', category: 'type' },
  { id: 'kw_type', label: 'tipo', category: 'type', editable: true },
  { id: 'kw_type_str', label: 'string', category: 'type', editable: true },
  { id: 'kw_task', label: 'Task', category: 'type', editable: true },
  // Symbols
  { id: 'sym_open_brace', label: '{', category: 'symbol' },
  { id: 'sym_close_brace', label: '}', category: 'symbol' },
  { id: 'sym_open_paren', label: '(', category: 'symbol' },
  { id: 'sym_close_paren', label: ')', category: 'symbol' },
  { id: 'sym_semicolon', label: ';', category: 'symbol' },
  { id: 'sym_comma', label: ',', category: 'symbol' },
  { id: 'sym_dot', label: '.', category: 'symbol' },
  { id: 'sym_colon', label: ':', category: 'symbol' },
  // Operators
  { id: 'op_assign', label: '=', category: 'operator' },
  { id: 'op_eq', label: '==', category: 'operator' },
  { id: 'op_lambda', label: '=>', category: 'operator' },
  { id: 'op_gt', label: '>', category: 'operator' },
  { id: 'op_quest', label: '?', category: 'operator' },
  { id: 'op_mult', label: '*', category: 'operator' },
  { id: 'op_interp', label: '$', category: 'operator' },
  // Editable identifiers
  { id: 'id_class', label: 'NomeClasse', category: 'identifier', editable: true },
  { id: 'id_method', label: 'metodo', category: 'identifier', editable: true },
  { id: 'id_var', label: 'variavel', category: 'identifier', editable: true },
  { id: 'id_name', label: 'nome', category: 'identifier', editable: true },
  { id: 'id_item', label: 'item', category: 'identifier', editable: true },
  { id: 'id_coll', label: 'colecao', category: 'identifier', editable: true },
  { id: 'id_p', label: 'parametro', category: 'identifier', editable: true },
  { id: 'id_list', label: 'lista', category: 'identifier', editable: true },
  { id: 'id_m', label: 'metodo', category: 'identifier', editable: true },
  { id: 'id_x', label: 'x', category: 'identifier', editable: true },
  { id: 'id_ctor', label: 'Construtor', category: 'identifier', editable: true },
  { id: 'id_dict', label: 'dicionario', category: 'identifier', editable: true },
  // Literals
  { id: 'val_string', label: '"texto"', category: 'literal', editable: true },
  { id: 'val_str', label: '"texto"', category: 'literal', editable: true },
  { id: 'val_def', label: '"default"', category: 'literal', editable: true },
  { id: 'val_10', label: '10', category: 'literal', editable: true },
  { id: 'val_k', label: '0', category: 'literal', editable: true },
  { id: 'val_v', label: '"valor"', category: 'literal', editable: true },
  { id: 'v1', label: 'valor1', category: 'literal', editable: true },
  { id: 'v2', label: 'valor2', category: 'literal', editable: true },
  { id: 'lit_true', label: 'true', category: 'literal' },
  { id: 'lit_false', label: 'false', category: 'literal' },
  { id: 'lit_null', label: 'null', category: 'literal' },
];

export const PYTHON_TOKENS: SyntaxToken[] = [
  // Keywords
  { id: 'kw_def', label: 'def', category: 'keyword' },
  { id: 'kw_if', label: 'if', category: 'keyword' },
  { id: 'kw_else', label: 'else', category: 'keyword' },
  { id: 'kw_for', label: 'for', category: 'keyword' },
  { id: 'kw_in', label: 'in', category: 'keyword' },
  { id: 'kw_ret', label: 'return', category: 'keyword' },
  { id: 'kw_class', label: 'class', category: 'keyword' },
  { id: 'kw_imp', label: 'import', category: 'keyword' },
  { id: 'kw_lam', label: 'lambda', category: 'keyword' },
  { id: 'kw_try', label: 'try', category: 'keyword' },
  { id: 'kw_exc', label: 'except', category: 'keyword' },
  { id: 'kw_and', label: 'and', category: 'keyword' },
  { id: 'kw_with', label: 'with', category: 'keyword' },
  { id: 'kw_as', label: 'as', category: 'keyword' },
  // Symbols
  { id: 'sym_open_paren', label: '(', category: 'symbol' },
  { id: 'sym_close_paren', label: ')', category: 'symbol' },
  { id: 'sym_open_bracket', label: '[', category: 'symbol' },
  { id: 'sym_close_bracket', label: ']', category: 'symbol' },
  { id: 'sym_open_brace', label: '{', category: 'symbol' },
  { id: 'sym_close_brace', label: '}', category: 'symbol' },
  { id: 'sym_colon', label: ':', category: 'symbol' },
  { id: 'sym_comma', label: ',', category: 'symbol' },
  { id: 'sym_dot', label: '.', category: 'symbol' },
  // Operators
  { id: 'op_assign', label: '=', category: 'operator' },
  { id: 'op_gt', label: '>', category: 'operator' },
  { id: 'op_mult', label: '*', category: 'operator' },
  // Identifiers
  { id: 'id_func', label: 'funcao', category: 'identifier', editable: true },
  { id: 'id_name', label: 'nome', category: 'identifier', editable: true },
  { id: 'id_var', label: 'variavel', category: 'identifier', editable: true },
  { id: 'id_list', label: 'lista', category: 'identifier', editable: true },
  { id: 'id_p', label: 'parametro', category: 'identifier', editable: true },
  { id: 'id_item', label: 'item', category: 'identifier', editable: true },
  { id: 'id_init', label: '__init__', category: 'identifier', editable: true },
  { id: 'id_self', label: 'self', category: 'identifier', editable: true },
  { id: 'id_meth', label: 'metodo', category: 'identifier', editable: true },
  { id: 'id_mod', label: 'modulo', category: 'identifier', editable: true },
  { id: 'id_x', label: 'x', category: 'identifier', editable: true },
  { id: 'id_err', label: 'Erro', category: 'identifier', editable: true },
  { id: 'id_parent', label: 'Pai', category: 'identifier', editable: true },
  { id: 'id_a', label: 'a', category: 'identifier', editable: true },
  { id: 'id_b', label: 'b', category: 'identifier', editable: true },
  { id: 'id_f', label: 'f', category: 'identifier', editable: true },
  { id: 'id_type', label: 'tipo', category: 'identifier', editable: true },
  // Literals
  { id: 'val_str', label: '"texto"', category: 'literal', editable: true },
  { id: 'prefix', label: 'f', category: 'literal' },
  { id: 'val', label: '0', category: 'literal', editable: true },
  { id: 'val_2', label: '2', category: 'literal', editable: true },
  { id: 'v1', label: '"val1"', category: 'literal', editable: true },
  { id: 'v2', label: '"val2"', category: 'literal', editable: true },
  { id: 'key', label: '"chave"', category: 'literal', editable: true },
];

export const TYPESCRIPT_TOKENS: SyntaxToken[] = [
  // Keywords
  { id: 'kw_let', label: 'let', category: 'keyword' },
  { id: 'kw_const', label: 'const', category: 'keyword' },
  { id: 'kw_func', label: 'function', category: 'keyword' },
  { id: 'kw_interface', label: 'interface', category: 'keyword' },
  { id: 'kw_enum', label: 'enum', category: 'keyword' },
  { id: 'kw_type', label: 'type', category: 'keyword' },
  { id: 'kw_priv', label: 'private', category: 'keyword' },
  { id: 'kw_ro', label: 'readonly', category: 'keyword' },
  { id: 'kw_any', label: 'any', category: 'keyword' },
  { id: 'kw_void', label: 'void', category: 'keyword' },
  { id: 'kw_as', label: 'as', category: 'keyword' },
  { id: 'kw_int', label: 'interface', category: 'keyword' },
  { id: 'kw_ext', label: 'extends', category: 'keyword' },
  { id: 'kw_ns', label: 'namespace', category: 'keyword' },
  { id: 'kw_ctor', label: 'constructor', category: 'keyword' },
  { id: 'kw_pub', label: 'public', category: 'keyword' },
  { id: 'kw_abs', label: 'abstract', category: 'keyword' },
  { id: 'kw_class', label: 'class', category: 'keyword' },
  // Types
  { id: 'kw_array', label: 'Array', category: 'type' },
  // Symbols
  { id: 'sym_colon', label: ':', category: 'symbol' },
  { id: 'sym_semicolon', label: ';', category: 'symbol' },
  { id: 'sym_open_brace', label: '{', category: 'symbol' },
  { id: 'sym_close_brace', label: '}', category: 'symbol' },
  { id: 'sym_open_paren', label: '(', category: 'symbol' },
  { id: 'sym_close_paren', label: ')', category: 'symbol' },
  { id: 'sym_open_bracket', label: '[', category: 'symbol' },
  { id: 'sym_close_bracket', label: ']', category: 'symbol' },
  { id: 'sym_lt', label: '<', category: 'symbol' },
  { id: 'sym_gt', label: '>', category: 'symbol' },
  { id: 'sym_comma', label: ',', category: 'symbol' },
  { id: 'sym_dot', label: '.', category: 'symbol' },
  // Operators
  { id: 'op_assign', label: '=', category: 'operator' },
  { id: 'op_opt', label: '?', category: 'operator' },
  { id: 'op_union', label: '|', category: 'operator' },
  { id: 'op_and', label: '&', category: 'operator' },
  { id: 'op_arrow', label: '=>', category: 'operator' },
  // Identifiers
  { id: 'id_name', label: 'nome', category: 'identifier', editable: true },
  { id: 'id_var', label: 'variavel', category: 'identifier', editable: true },
  { id: 'id_prop', label: 'propriedade', category: 'identifier', editable: true },
  { id: 'id_p', label: 'parametro', category: 'identifier', editable: true },
  { id: 'id_attr', label: 'atributo', category: 'identifier', editable: true },
  { id: 'id_obj', label: 'objeto', category: 'identifier', editable: true },
  { id: 'id_child', label: 'Filho', category: 'identifier', editable: true },
  { id: 'id_parent', label: 'Pai', category: 'identifier', editable: true },
  { id: 'id_t', label: 'T', category: 'identifier', editable: true },
  { id: 'id_res', label: 'resultado', category: 'identifier', editable: true },
  { id: 'id_1', label: 'iden1', category: 'identifier', editable: true },
  { id: 'id_2', label: 'iden2', category: 'identifier', editable: true },
  { id: 'id_p1', label: 'p1', category: 'identifier', editable: true },
  { id: 'id_p2', label: 'p2', category: 'identifier', editable: true },
  { id: 't1', label: 't1', category: 'identifier', editable: true },
  { id: 't2', label: 't2', category: 'identifier', editable: true },
  // Literals
  { id: 'val_str', label: '"texto"', category: 'literal', editable: true },
  { id: 'val_num', label: '0', category: 'literal', editable: true },
  { id: 'v1', label: '"val1"', category: 'literal', editable: true },
  { id: 'v2', label: '"val2"', category: 'literal', editable: true },
];

export const LANGUAGE_TOKENS: Record<Language, SyntaxToken[]> = {
  javascript: JAVASCRIPT_TOKENS,
  java: JAVA_TOKENS,
  csharp: CSHARP_TOKENS,
  python: PYTHON_TOKENS,
  typescript: TYPESCRIPT_TOKENS,
};

// ─────────────────────────────────────────────
// Token category colors
// ─────────────────────────────────────────────
export const TOKEN_CATEGORY_COLORS: Record<string, { bg: string; border: string; text: string }> = {
  keyword:    { bg: '#1E1B4B', border: '#6366F1', text: '#A5B4FC' },
  modifier:   { bg: '#1A1040', border: '#8B5CF6', text: '#C4B5FD' },
  type:       { bg: '#042F2E', border: '#14B8A6', text: '#5EEAD4' },
  symbol:     { bg: '#1C1917', border: '#78716C', text: '#D4CCC7' },
  operator:   { bg: '#172554', border: '#3B82F6', text: '#93C5FD' },
  identifier: { bg: '#052E16', border: '#22C55E', text: '#86EFAC' },
  literal:    { bg: '#431407', border: '#F97316', text: '#FED7AA' },
};

// ─────────────────────────────────────────────
// Language metadata
// ─────────────────────────────────────────────
export type LanguageInfo = {
  id: Language;
  label: string;
  color: string;
  accent: string;
  icon: string; // MaterialCommunityIcons name
};

export const LANGUAGES: LanguageInfo[] = [
  {
    id: 'javascript',
    label: 'JavaScript',
    color: '#854d0e',
    accent: '#FDE047',
    icon: 'language-javascript',
  },
  {
    id: 'python',
    label: 'Python',
    color: '#1e3a8a',
    accent: '#60a5fa',
    icon: 'language-python',
  },
  {
    id: 'typescript',
    label: 'TypeScript',
    color: '#1e3a8a',
    accent: '#3b82f6',
    icon: 'language-typescript',
  },
  {
    id: 'java',
    label: 'Java',
    color: '#7c2d12',
    accent: '#FB923C',
    icon: 'language-java',
  },
  {
    id: 'csharp',
    label: 'C#',
    color: '#312e81',
    accent: '#818CF8',
    icon: 'language-csharp',
  },
];
